name: Infraestructure

on:
  push:
    branches: ["main"]
    paths: ["infraestructure/Develop/**"]

permissions:
  id-token: write
  contents: write
  pull-requests: write
    
jobs:

  tfsec:

    name: tfsec
    runs-on: ubuntu-latest

    steps:

      - name: Clone repo
        uses: actions/checkout@v4

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0


  terraform_format:

    name: Check Terraform file are formatted correctly
    needs: [tfsec]
    runs-on: ubuntu-latest
    
    steps:

      - name: Clone repo
        uses: actions/checkout@v4
        
      - name: hashicorp setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ steps.generate_token.outputs.token }}
          approvers: ${{ secrets.APPROVAL }}
          minimum-approvals: 1  

      - name: Terraform Apply
        id: apply
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: terraform apply -auto-approve  

        